name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"


kv_namespaces = [
  { binding = "NOTES", id = "c3e64ab21912490199417691538d3121" },
  { binding = "SHARE", id = "8f29990f14674d69a86e0acc933804fa" }
]
